apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: koxy48wyb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: koxy48wyb-go 
  name: koxy48wyb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: koxy48wyb-go 
