apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: koxy48wyb-go 
  janus-idp.io/tekton: koxy48wyb-go
  backstage.io/kubernetes-id: koxy48wyb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: koxy48wyb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml